friends = ['Саша','Маша','Даша']
print(f'Hello {friends[0]}')
print(f'Hello {friends[1]}')
print(f'Hello {friends[2]}')
friend_leave = friends.pop()
print(f'Goodbay {friend_leave}')
print(f'Hello {friends[0]}')
print(f'Hello {friends[1]}')
print('новые гости')
friends.insert(0,'Клаша')
friends.insert(2,'Жора')
friends.append('Аркаша')
print(f'Hello {friends[0]}')
print(f'Hello {friends[1]}')
print(f'Hello {friends[2]}')
print(f'Hello {friends[3]}')
print(f'Hello {friends[4]}')
print('Только 2 гостя')
friend_leave=friends.pop()
print(f'Goodbay {friend_leave}')
friend_leave =friends.pop()
print(f'Goodbay {friend_leave}')
friend_leave =friends.pop()
print(f'Goodbay {friend_leave}')
print(f'кушать подано {friends[0]}')
print(f'кушать подано {friends[1]}')
friends.remove('Клаша')
del friends[0]
print(friends)